-- Supplier Table

CREATE TABLE supplier (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    address VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL
);

-- Medicine Table

CREATE TABLE medicine (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(50) NOT NULL,
    dose_unit VARCHAR(10) NOT NULL,
    dose_amount DECIMAL(10, 2) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    expiry_date DATE NOT NULL,
    supplier_id INT,
    FOREIGN KEY (supplier_id) REFERENCES supplier(id)
);

-- Order Table

CREATE TABLE orders (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_date DATE NOT NULL,
    status VARCHAR(50) NOT NULL,
    delivery_date DATE,
    supplier_id INT,
    FOREIGN KEY (supplier_id) REFERENCES supplier(id)
);

-- Order Details Table

CREATE TABLE order_details (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id INT,
    medicine_id INT,
    quantity INT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (order_id) REFERENCES orders(id),
    FOREIGN KEY (medicine_id) REFERENCES medicine(id)
);

-- Inventory Table

CREATE TABLE inventory (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    medicine_id INT,
    quantity INT NOT NULL,
    last_updated DATE NOT NULL,
    FOREIGN KEY (medicine_id) REFERENCES medicine(id)
);

-- Customer Table

CREATE TABLE customers (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    address VARCHAR(100) NOT NULL
);

-- Prescription Table
CREATE TABLE prescriptions (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_id INT,
    prescription_date DATE NOT NULL,
    FOREIGN KEY (customer_id) REFERENCES customers(id)
);

-- Prescription Details Table
CREATE TABLE prescription_details (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    prescription_id INT,
    medicine_id INT,
    quantity INT NOT NULL,
    FOREIGN KEY (prescription_id) REFERENCES prescriptions(id),
    FOREIGN KEY (medicine_id) REFERENCES medicine(id)
);

-- Customer Orders Table

CREATE TABLE customer_orders (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_date DATE NOT NULL,
    customer_id INT,
    prescription_id INT,
    FOREIGN KEY (customer_id) REFERENCES customers(id)
    FOREIGN KEY (prescription_id) REFERENCES prescriptions(id)
);

-- Customer Order Detail Table

CREATE TABLE customer_order_details (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    quantity INT NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    medicine_id INT,
    customer_order_id INT,
    FOREIGN KEY (customer_order_id) REFERENCES customer_orders(id),
    FOREIGN KEY (medicine_id) REFERENCES medicine(id)
);

-- Employee Table

CREATE TABLE employees (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    address VARCHAR(100) NOT NULL,
    salary DECIMAL(10,2) NOT NULL,
    role VARCHAR(50) NOT NULL
);
